# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.4.0
_src_path: git@ci.tno.nl:pet/pet-project-templates/python.git
license: apache2.0
package_name: tno.mpc.demo.futurepet
package_title: Secure Multi-Party Computation (MPC) - Demo - Futurepet
package_type: simple
project_description: Demonstrating the PET Lab to FCINet
project_url: ''
